/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap_testing;

import hashmap_testing.datastructure.AbstractVariableAddress;
import hashmap_testing.datastructure.SimpleVariableAddress;
import hashmap_testing.datastructure.VariableAddressPlcWildcard;
import hashmap_testing.datastructure.VariableAddressWildcard;

public class App {

    public static void main(String[] args) {
        AbstractVariableAddress addressAllPlcs = new VariableAddressWildcard();
        AbstractVariableAddress addressPlcAllVariables = new VariableAddressPlcWildcard(54);
        AbstractVariableAddress address = new SimpleVariableAddress(54, 1, 2002);
        
        System.out.println("hashcode for magic address all plcs - " + addressAllPlcs.hashCode());
        System.out.println("hashcode for magic address plc all variables - " + addressPlcAllVariables.hashCode());
        System.out.println("hashcode for address - " + address.hashCode());
    }
}
